Categories:
  - Multimedia
License: MIT
AuthorName: bas080
SourceCode: https://github.com/bas080/auto-sleep-droid
IssueTracker: https://github.com/bas080/auto-sleep-droid/issues
Changelog: https://github.com/bas080/auto-sleep-droid/releases
