build:
  maxIssues: 0
  weights:
    complexity: 1

config:
  validation: true

complexity:
  active: true
  excludes: ['**/test/**']
  CognitiveComplexMethod:
    active: true
    threshold: 10
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: true
    threshold: 10
  CyclomaticComplexMethod:
    active: true
    threshold: 10
  LargeClass:
    active: true
    threshold: 1800
  LongMethod:
    active: true
    threshold: 50
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6
    ignoreDataClasses: true
  NestedBlockDepth:
    active: true
    threshold: 4
  TooManyFunctions:
    active: true
    thresholdInFiles: 120
    thresholdInClasses: 110
    thresholdInObjects: 20

empty-blocks:
  active: true
  excludes: ['**/test/**']

exceptions:
  active: true
  excludes: ['**/test/**']

performance:
  active: true
  excludes: ['**/test/**']

potential-bugs:
  active: true
  excludes: ['**/test/**']

style:
  active: true
  excludes: ['**/test/**']
  MaxLineLength:
    maxLineLength: 160
  MagicNumber:
    active: true
    ignoreNumbers: ['-15', '-1', '0', '1', '2', '3', '4', '5', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '20', '21', '23', '24', '25', '28', '29', '30', '31', '32', '33', '35', '40', '42', '45', '50', '55', '59', '60', '64', '70', '70L', '80', '100', '101', '102', '106', '107', '110', '120', '255', '600', '1000', '1024', '1440', '1800', '3600000', '30000', '60000', '30000L', '60000L', '0.2', '0.2f', '0.38f', '0.3f', '0.5', '1.0', '1.0f', '1.2']
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
